-- File generated by the BNF Converter (bnfc 2.9.4).

{-# LANGUAGE GeneralizedNewtypeDeriving #-}

-- | The abstract syntax of language LL.

module AbsLL where

import Prelude (String)
import qualified Prelude as C (Eq, Ord, Show, Read)
import qualified Data.String

data Def = Def Ident Term
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data Term
    = TLambda Ident Term
    | TLamBang Ident Term
    | TVar Ident
    | TBang Term
    | TApp Term Term
  deriving (C.Eq, C.Ord, C.Show, C.Read)

newtype Ident = Ident String
  deriving (C.Eq, C.Ord, C.Show, C.Read, Data.String.IsString)

