## File generated by the BNF Converter (bnfc 2.9.4).

# Makefile for building the parser and test program.

GHC        = ghc
HAPPY      = happy
HAPPY_OPTS = --array --info --ghc --coerce
ALEX       = alex
ALEX_OPTS  = --ghc

# List of goals not corresponding to file names.

.PHONY : all clean distclean

# Default goal.

all : TestLL Main

# Rules for building the parser.

AbsLL.hs LexLL.x ParLL.y PrintLL.hs TestLL.hs : LL.cf
	bnfc --haskell LL.cf

%.hs : %.y
	${HAPPY} ${HAPPY_OPTS} $<

%.hs : %.x
	${ALEX} ${ALEX_OPTS} $<

TestLL : AbsLL.hs LexLL.hs ParLL.hs PrintLL.hs TestLL.hs
	${GHC} ${GHC_OPTS} $@

Main : AbsLL.hs LexLL.hs ParLL.hs PrintLL.hs Main.hs Reduce.hs Env.hs CheckWellFormedness.hs
	${GHC} ${GHC_OPTS} $@

# Rules for cleaning generated files.

clean :
	-rm -f *.hi *.o *.log *.aux *.dvi

distclean : clean
	-rm -f AbsLL.hs AbsLL.hs.bak ComposOp.hs ComposOp.hs.bak DocLL.txt DocLL.txt.bak ErrM.hs ErrM.hs.bak LayoutLL.hs LayoutLL.hs.bak LexLL.x LexLL.x.bak ParLL.y ParLL.y.bak PrintLL.hs PrintLL.hs.bak SkelLL.hs SkelLL.hs.bak TestLL.hs TestLL.hs.bak XMLLL.hs XMLLL.hs.bak ASTLL.agda ASTLL.agda.bak ParserLL.agda ParserLL.agda.bak IOLib.agda IOLib.agda.bak Main.agda Main.agda.bak LL.dtd LL.dtd.bak TestLL LexLL.hs ParLL.hs ParLL.info ParDataLL.hs Makefile


# EOF
